### ISSUE TITLE
Support for Wagtail 3 and Django 4

### ISSUE THREAD

**Issue by m-aciek** [Gandi/wagtail-oauth2#3]
pip downgrades the Wagtail and Django versions when adding wagtail-oauth2 to the environment at the moment. Would it be possible to:
* remove the upper versions constraints in pyproject.toml
* add support to the newer frameworks versions if needed?

Thank you for sharing library's code to public.

**Comment by Themimitoof** [comment]
Hello @m-aciek,

Thanks for the report!

Wagtail 3 is still in release candidate but as we plan to upgrade our projects to Wagtail 3 when it will be available, I created a ticket internally to fix the problem.

**Comment by m-aciek** [comment]
As a reference I'm sharing a link to a discussion against the dependencies versions capping: https://iscinumpy.dev/post/bound-version-constraints/.

**Comment by andrewlangemann** [comment]
Wagtail 3 is now released - can this get updated?

**Comment by Themimitoof** [comment]
Hello, I've just made the needed changes to make the plugin working on Wagtail 3.0 and Django 4.0. A 1.0.0 release has been pushed on PyPi. :)
